Tags:[python, 异步]

### python中的异步

#### 理解yield

粗略知道yield可以作为一个函数返回值：

```python
def addlist(alist):
	for i in alist:
		yield i+1
	
alist=[1,2,3,4]
for x in addlist(alist):
	print(x)
```

输出：2，3，4，5

某个函数包含了yield，这意味着这个函数已经是一个Generator，它的执行会和其他普通的函数有很多不同。

```python
def h():
	print('aaa')
	yield 5
h()
<generator object h at 0x108e95a50>
```

这个h()并不能输出aaa,因为它有yield表达式, 是个生成器。

我们通过`next(`语句让它执行。

##### `next()`

next()语句将恢复Generator执行，并直到下一个yield表达式处.

```python
def h():
	print("aaa")
	yield 5
	print("bbb")
	yield 12
c=h()
print c.next()
print c.next()
print c.next()

out: 
aaa
5
bbb
12
Traceback (most recent call last):
  File "yield.py", line 10, in <module>
    print c.next()
StopIteration
```

输出: aaa 5

再次调用next()时，会找到下一个yield，输出bbb 12.

最后调用next()出现异常, 因为后面没有yield.



##### **yield是表达式**

`m=yield 5`

表达式(yield 5)的返回值将赋值给m，所以，认为 m = 5 是错误的。

```python
def h():
    print("aaa")
    m = yield 5
    print m
    print("bbb")
    yield 12

c = h()
print c.next() # 这里加print 才能打印出m的值
print c.next()

out:
aaa
5
None  # m 并不是5
bbb
12
```

那么如何获取(yield 5)的返回值呢？需要用到后面要介绍的send(msg)方法。



##### send(msg)

其实next()和send()在一定意义上作用是相似的，区别是send()可以传递yield表达式的值进去，而next()不能传递特定的值，只能传递None进去。因此，我们可以看做

c.next() 和 c.send(None) 作用是一样的。

```python
def h():
    print("aaa")  
    m=yield 5   
    print(m)
    d=yield 12
    print(d)
    print("bbb")
    n=yield 13

c=h()
print c.next() #c.next() 和 c.send(None) 作用是一样的。
print c.next() #yield 5被赋予了None
print c.send('ccc')#yeild 12表达式被赋予了ccc
```

输出：

```
aaa
5
None
12
ccc
bbb
13
```

**send方法等参数会成为暂停的yield表达式的值。**

**注意：**第一次调用时，请使用next()语句或是send(None)，不能使用send发送一个非None的值，否则会出错的，因为没有yield语句来接收这个值。

##### send(msg) 与 next()的返回值

end(msg) 和 next()是有返回值的，它们的返回值很特殊，返回的是**下一个**yield表达式的参数。比如yield 5，则返回 5 。这可以看出我们第一个代码示例中为什么输出5了。

但是有send(msg)传入值，则会返回传入的值。

##### 中断Generator

可以通过throw抛出一个GeneratorExit异常来终止Generator。Close()方法作用是一样的，其实内部它是调用了throw(GeneratorExit)的。我们看：

```python
def close(self):
    try:
        self.throw(GeneratorExit)
    except (GeneratorExit, StopIteration):
        pass
    else:
        raise RuntimeError("generator ignored GeneratorExit")
# Other exceptions are not caught
```

因此，当我们调用了close()方法后，再调用next()或是send(msg)的话会抛出一个异常.



### 协程

子程序，或者称为函数，在所有语言中都是层级调用，比如A调用B，B在执行过程中又调用了C，C执行完毕返回，B执行完毕返回，最后是A执行完毕。

所以子程序调用是通过栈实现的，一个线程就是执行一个子程序。

协程看上去也是子程序，但执行过程中，在子程序内部可中断，然后转而执行别的子程序，在适当的时候再返回来接着执行。

注意，在一个子程序中中断，去执行其他子程序，不是函数调用，有点类似CPU的中断。

#### yield

协程是yield实现的，和生成器类似，不过协程中都是data = yield中的形式，调用方对协程使用send(data)方法，如上方的h函数。



#### 一个简单的协程

```python
#coding:utf8
def simple_coroutine():
    print "协程开始"
    x = yield
    print "协程接受到数据：", x

coro = simple_coroutine()
print coro
print next(coro) # 首先要用next函数来启动生成器， 让其停止在yield，否则没法发送send()的数据。
print coro.send(666)
```

Out: 

```python
<generator object simple_coroutine at 0x10e159aa0> #协程使用生成器函数定义,定义体中有yield关键字。
协程开始
None # yield 右边没有返回值，隐式为None
协程接受到数据： 666
Traceback (most recent call last):
  File "coroutine.py", line 10, in <module>
    print coro.send(666)
StopIteration
```

next 函数那一步通常成为预激。

一个预激装饰器：

```python
from functools import wraps
def coroutine(func):
    @wraps(func)
    def primer(*args, **kwargs):
        gen=func(*args, **kwargs)
        next(gen)
        return gen
    return primer
```





#### 协程的状态

* GEN_CREATED 等待开始执行
* GEN_RUNNING 解释器正在执行
* GEN_SUSPENDED 在yield表达式处
* GEN_CLOSED 执行结束

协程可以身处四个状态中的一个， 当前状态可以使用inspect.getgeneratorstate()函数来确定， 会返回上述字符串中的一个

```python
my_coro = simple_coro()
from inspect import getgeneratorstate
getgeneratorstate(my_coro)
'GEN_CREATED'
```



#### 终止协程和异常处理

在生成器上调用两个方法，显式的把异常发送给协程。

* Generator.throw(exc_type[, exc_value[, traceback]])

  使生成器在暂停的yield表达式处抛出指定的异常。

  如果生成器处理了抛出的异常， 代码会向前执行到下一个yield表达式， 产出值返回给generator.throw.

  如果没有处理这个异常， 异常会向上冒泡，传到调用方等上下文中。

* Gernerator.close()

  使生成器在暂停的yield表达式处抛出GeneratorExit异常。

  如果生成器没有处理这个异常，或者抛出了StopIteration异常（通常运行到结尾），调用方不会出错。

  一般都不会处理这个异常。



```python
#coding:utf8

#from inspect import getgeneratorstate

class DemoException(Exception):
    """为本次demo所做的异常"""

def demo_exc_handling():
    print "协程开始"
    while True:
        try:
            x = yield
        except DemoException:
            print "捕获到DemoException"
        else:
            print "接收到值: ", x
    raise RuntimeError(" 这里永远也不会跑") # 未处理的异常会中止那个无限循环，那时协程会立即终止。

print '===== 正常执行 ====='
coro = demo_exc_handling()
print next(coro)
print coro.send(1)
print coro.close()
#print getgeneratorstate(coro)

print '====== 传入DemoException异常 ======='
coro = demo_exc_handling()
print next(coro)
print coro.send(1)
coro.throw(DemoException)
print coro.send(2)
#print getgeneratorstate(coro)

print '====== 传入无法处理的异常 ========'
coro = demo_exc_handling()
print next(coro)
print coro.send(1)
coro.throw(ZeroDivisionError)
#print getgeneratorstate(coro)

out:
===== 正常执行 =====
协程开始
None
接收到值:  1
None
None
====== 传入DemoException异常 =======
协程开始
None
接收到值:  1
None
捕获到DemoException
接收到值:  2
None
====== 传入无法处理的异常 ========
协程开始
None
接收到值:  1
None
Traceback (most recent call last):
  File "coro_exc.py", line 37, in <module>
    coro.throw(ZeroDivisionError)
  File "coro_exc.py", line 12, in demo_exc_handling
    x = yield
ZeroDivisionError
```



不管协程怎样处理异常都想做些清理工作：

```python
class DemoException(Exception):
    """为本次demo所做的异常"""

def demo_exc_handling():
    print "协程开始"
    try:
        while True:
            try:
                x = yield
            except DemoException:
                print "捕获到DemoException"
            else:
                print "接收到值: ", x
    finally:
        print '协程结束'
```





#### 那和多线程比，协程有何优势？

最大的优势就是协程极高的执行效率。因为子程序切换不是线程切换，而是由程序自身控制，因此，没有线程切换的开销，和多线程比，线程数量越多，协程的性能优势就越明显。

第二大优势就是不需要多线程的锁机制，因为只有一个线程，也不存在同时写变量冲突，在协程中控制共享资源不加锁，只需要判断状态就好了，所以执行效率比多线程高很多。

因为协程是一个线程执行，那怎么利用多核CPU呢？最简单的方法是多进程+协程，**既充分利用多核**，又充分发挥协程的高效率，可获得极高的性能。

Python对协程的支持是通过generator实现的。

#### 生产者消费者模型

传统的生产者-消费者模型是一个线程写消息，一个线程取消息，通过锁机制控制队列和等待，但一不小心就可能死锁。

如果改用协程，生产者生产消息后，直接通过`yield`跳转到消费者开始执行，待消费者执行完毕后，切换回生产者继续生产，效率极高：

```python
def consumer():
    r = ''
    while True:
        n = yield r
        if not n:
            return
        print('[消费者] 消费了 %s...' % n)
        r = '200 OK'

def produce(c):
    c.send(None)
    n = 0
    while n < 5:
        n = n + 1
        print('[生产者] 生产了 %s...' % n)
        r = c.send(n)
        print('[生产者] 消费者返回状态: %s' % r)
    c.close()

c = consumer()
produce(c)
```

输出：

![](http://ojynuthay.bkt.clouddn.com/custormReturn.png)

思路分析：

- c=consumer() 只是赋值，函数并不会执行
- c.send(None),等同于`c.__next__()`，consumer()执行到n=yield '',则停止，继续produce()的语句
- n=0, while ...输出生产者生产了1
- r=c.send(1) ,将yield表达式赋值为1，此时n是1，if not 内不执行，然后打印消费者。
- 此时customer()中r='200 ok',send()的返回值是下个yield表达式的参数。所以produce()中r=send(n)等于‘200 ok'
- close()关闭协程。

### asynico

`asyncio`是Python 3.4版本引入的标准库，直接内置了对异步IO的支持。

用`asyncio`提供的`@asyncio.coroutine`可以把一个generator标记为coroutine类型，然后在coroutine内部用`yield from`调用另一个coroutine实现异步操作。

`asyncio`的编程模型就是一个消息循环。我们从`asyncio`模块中直接获取一个`EventLoop`的引用，然后把需要执行的协程扔到`EventLoop`中执行，就实现了异步IO。

用`asyncio`实现`Hello world`代码如下：

```python
import asyncio

@asyncio.coroutine #把一个generator标记为coroutine类型，然后，我们就把这个coroutine扔到EventLoop中执行。
def hello():
    print('Hello world')
    r=yield from asyncio.sleep(3)
    print('Hello again')

loop=asyncio.get_event_loop()
loop.run_until_complete(hello())
loop.close()
```

两个coroutine:

```python
import threading
import asyncio

@asyncio.coroutine
def hello():
    print('Hello world! (%s)' % threading.currentThread())
    yield from asyncio.sleep(1)
    print('Hello again! (%s)' % threading.currentThread())

loop = asyncio.get_event_loop()
tasks = [hello(), hello()]
loop.run_until_complete(asyncio.wait(tasks))
loop.close()
```

![](http://ojynuthay.bkt.clouddn.com/asynchronous.png)



`hello()`会首先打印出`Hello world!`，然后，`yield from`语法可以让我们方便地调用另一个`generator`。由于`asyncio.sleep()`也是一个`coroutine`，所以线程不会等待`asyncio.sleep()`，而是直接中断并执行下一个消息循环。当`asyncio.sleep()`返回时，线程就可以从`yield from`拿到返回值（此处是`None`），然后接着执行下一行语句。

把`asyncio.sleep(1)`看成是一个耗时1秒的IO操作，在此期间，主线程并未等待，而是去执行`EventLoop`中其他可以执行的`coroutine`了，因此可以实现并发执行。



### async/await

用`asyncio`提供的`@asyncio.coroutine`可以把一个generator标记为coroutine类型，然后在coroutine内部用`yield from`调用另一个coroutine实现异步操作。

为了简化并更好地标识异步IO，从Python 3.5开始引入了新的语法`async`和`await`，可以让coroutine的代码更简洁易读。

请注意，`async`和`await`是针对coroutine的新语法，要使用新的语法，只需要做两步简单的替换：

1. 把`@asyncio.coroutine`替换为`async`；
2. 把`yield from`替换为`await`。

让我们对比一下上一节的代码：

```python
@asyncio.coroutine
def hello():
    print("Hello world!")
    r = yield from asyncio.sleep(1)
    print("Hello again!")
```

用新语法重新编写如下：

```python
async def hello():
    print("Hello world!")
    r = await asyncio.sleep(1)
    print("Hello again!")
```

 

https://blog.csdn.net/soonfly/article/details/78361819/